
---
title: "Determinations Around Lipids Analysis- Processing Adt. Vials - Summer Krill 2019"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Determinations Around Lipids Analysis Summer Krill 2019
Date: February 2021 (R notebook document)


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```



# Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(stringr)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
library(arsenal)
library(compareDF)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
library(gdata)
library(rsq)
library(doBy)
library(lme4)
library(lmerTest)
#Rnotebooks 
library(gridExtra)
library(kableExtra)

```




 
# 1.) Setting Working Directory
```{r 1.) Setting Working Directory }
#*********************************
## 1.) Setting Working Directory
#*********************************

#set working directory to the correct folder
setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_KRL_SMR2019_lipids")
```



# 2.) DF Creation
```{r 2.) Creating the Dataframe }

#*********************************
## 2.) Creating the intial Dataframe, dRESP
#*********************************
# 46 Vials Magic Number

# Sample Specifics
dSpecifics <- read.csv(file = "2021.02.08_sampleSpecifics_transposed.csv", stringsAsFactors = FALSE)
dim(dSpecifics)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# Lipids Percentage
dPercent <- read.csv(file = "2021.02.08_lipidsPercentage_transposed.csv", stringsAsFactors = FALSE)
dim(dPercent)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# Lipids Per Sample
dPerSample <- read.csv(file = "2021.02.08_ugLipidPerSample_transposed.csv", stringsAsFactors = FALSE)
dim(dPerSample)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# Lipids Per WWT
dWWT <- read.csv(file = "2021.02.08_ug.mgLipidPerWWT_transposed.csv", stringsAsFactors = FALSE)
dim(dWWT)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# Lipids Per Individual 
dIndividual <- read.csv(file = "2021.02.08_ugLipidPerIndividual_transposed.csv", stringsAsFactors = FALSE)
dim(dIndividual)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# TAG
dTAG <- read.csv(file = "2021.02.08_TAG_transposed.csv", stringsAsFactors = FALSE)
dim(dTAG)
#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

# Totals (Estimates)
dEstTotals <- read.csv(file = "2021.02.08_Totals_transposed.csv", stringsAsFactors = FALSE)
dim(dEstTotals)

#|- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |

```


## 2.a) Creating new Dataframe
```{r 2.a) Creating new Dataframe }

#*********************************
## 2.) Creating the intial Dataframe, dRESP
#*********************************
# 46 Vials Magic Number

dSpecifics <- as.factor(dSpecifics$Sample.ID)
dPercent <- as.factor(dPercent$Sample.ID)
dPerSample <- as.factor(dPerSample$Sample.ID)
dIndividual <- as.factor(dIndividul$Sample.ID)
dWWT <- as.factor(dWWT$Sample.ID)
dTAG <- as.factor(dTAG$Sample.ID)
dEstTotals <- as.factor(dEstTotals$Sample.ID)

dLipids <- merge(dSpecifics, dPercent, dPerSample, dIndividual, dWWT, dTAG, dEstTotals, by="Sample.ID")


```



























```{r}

```





```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT
